### ISSUE TITLE
Damned awful bowling fans everywhere!!

### ISSUE THREAD

**Issue by stefanhra** [xorrbit/fuckthejets#1]
fuckthejets.pego.ca told me I should go to Skullspace tonight (Oct 17) and assured me there would be no fucking intolerant tennis fans taking up all the parking spots. 

When I got to Skullspace there were Grotesque Golf Fans wondering around everywhere in their Idiotic Rugby jerseys and all the parking spots were filled with cars belonging to Fucking Yucky Handball Fans.

**Comment by xorrbit** [comment]
Fixed in d1161c60829ce0da42420c9d758d91396e1793dc ;)
